- name: create niri config dir
  file:
    path: "{{ ansible_env.HOME }}/.config/niri"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: copy niri config file
  copy:
    src: config.kdl
    dest: "{{ ansible_env.HOME }}/.config/niri"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
