- name: create niri config dir
  file:
    path: "{{ ansible_env.HOME }}/.config/niri"
    state: directory
    owner: chaos
    group: chaos

#- name: copy niri config file
#  copy:
#    src: config.kdl
#    dest: "{{ ansible_env.HOME }}/.config/niri"
#    owner: chaos
#    group: chaos
