- name: copy bashrc file
  copy:
    src: files/bashrc
    dest: /home/chaos/.bashrc
    owner: chaos
    group: chaos

- name: copy bash_profile file
  copy:
    src: files/bash_profile
    dest: /home/chaos/.bash_profile
    owner: chaos
    group: chaos

- name: copy inputrc file
  copy:
    src: files/inputrc
    dest: /home/chaos/.inputrc
    owner: chaos
    group: chaos

- name: copy gitignore file
  copy:
    src: files/gitignore
    dest: /home/chaos/.gitignore
    owner: chaos
    group: chaos

- name: copy aliases file
  copy:
    src: files/aliases
    dest: /home/chaos/.aliases
    owner: chaos
    group: chaos

- name: create bash_functions dir
  file:
    path: /home/chaos/.bash_functions
    state: directory
    owner: chaos
    group: chaos

- name: copy bash_functions file
  copy:
    src: files/flavor-light
    dest: /home/chaos/.bash_functions/flavor-light
    owner: chaos
    group: chaos

- name: copy bash_functions file
  copy:
    src: files/yazi-bash-wrapper
    dest: /home/chaos/.bash_functions/yazi-bash-wrapper
    owner: chaos
    group: chaos


