---
- hosts: localhost
  connection: local
  become: true
  vars:
    newuser_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33306135336635366336663832636432333133646133633263613531383165383937666438613033
          6635613461333463616466613263626533376530366364630a336363636462353361656332323933
          31613332333566303161353364363364323031386430313535373133376130626637313235343431
          3331636466646130390a646264613635323730313063643061326262656534306430663236656361
          6162


  tasks:
  - name: install packages
    package:
      name: 
        - htop
        - fd
        - bat
        - zoxide
        - ripgrep
        - repgrep
        - ripgrep-all
        - cronie
        - python-passlib

  - name: copy .bashrc file
    copy:
      src: files/bashrc
      dest: /home/chaos/.bashrc
      owner: chaos
      group: chaos


  - name: add ansible user
    user:
      name: ansiblor
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_ansiblor
      dest: /etc/sudoers.d/ansiblor
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: ansiblor
      minute: "*/10"
      job: ansible-pull --vault-password-file ~/.vault/vault_key -o -U https://github.com/chaosgity/ansible-desktop.git


  - name: Remove user newuser
    ansible.builtin.user:
      name: "newuser"
      state: absent
      remove: yes

