---
- hosts: localhost
  connection: local
  become: true


  tasks:
  - name: install packages
    package:
      name: 
        - htop
        - fd
        - bat
        - zoxide
        - ripgrep
        - repgrep
        - ripgrep-all
        - cronie
        - python-passlib
        - apparmor
        - vivid

