---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:

  - name: install reflector package
    pacman:
      name: reflector
      state: present
   
  roles:
#    - { role: yay, tags: yay }
#    - { role: shelly, tags: shelly}
    - { role: configure, tags: configure }
    - { role: pacman, tags: pacman }
    - { role: rustup, tags: rustup }
#   - { role: cronie, tags: cronie }
#   - { role: ansible_user, tags: ansible_user }
    - { role: base, tags: base }
    - { role: bash, tag: bash }
    - { role: desktop, tags: desktop }
    - { role: niri, tags: niri }
    - { role: alacritty, tags: alacritty }
    - { role: mpv, tag: mpv }
#    - { role: walker, tag: walker }
#    - { role: ashell, tag: ashell }
    - { role: snapd, tag: snapd }
