---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:

    # Fix full /tmp when installing lots of AUR
    - name: temp increase /tmp size
      tags: always
      shell: mount -o remount,size=5G,noatime /tmp

    - name: install reflector package
      pacman:
        name: reflector
        state: present

    - name: Create AUR builder user
      ansible.builtin.user:
        name: aurbuilder
        groups: wheel
        create_home: true
    
    - name: Allow aurbuilder to use pacman without password
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/aurbuilder
        line: "aurbuilder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
        create: true
        mode: '0440'
        validate: 'visudo -cf %s'

    - name: Check if yay is installad
      ansible.builtin.command: which yay
      register: yay_check
      changed_when: false
      failed_when: false

    - name: Install yay AUR helper
      when: yay_check.rc != 0
      become_user: aurbuilder
      block:
        - name: Clone yay repository
          ansible.builtin.git:
            repo: https://aur.archlinux.org/yay-bin.git
            dest: /tmp/yay-bin
        
        - name: Build and install yay
          ansible.builtin.command: makepkg -si --noconfirm
          args:
            chdir: /tmp/yay-bin
          changed_when: true  


  roles:
    - { role: configure, tags: configure }
    - { role: pacman, tags: pacman }
    - { role: rustup, tags: rustup }
    - { role: cronie, tags: cronie }
    - { role: ansible_user, tags: ansible_user }
    - { role: base, tags: base }
    - { role: bash, tag: bash }
    - { role: desktop, tags: desktop }
    - { role: mpv, tag: mpv }
