---
- hosts: localhost
  connection: local
  become: true


  tasks:
  - name: install packages
    package:
      name: 
        - htop
        - fd
        - bat
        - zoxide
        - ripgrep
        - repgrep
        - ripgrep-all
        - cronie

  - name: copy .bashrc file
    copy:
      src: files/bashrc
      dest: /home/chaos/.bashrc
      owner: chaos
      group: chaos


  - name: add ansible user
    user:
      name: ansiblor
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_ansiblor
      dest: /etc/sudoers.d/ansiblor
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: ansiblor
      minute: "*/10"
      job: ansible-pull --vault-password-file ~/.vault/vault_key -o -U https://github.com/chaosgity/ansible-desktop.git

