---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:

    # Fix full /tmp when installing lots of AUR
    - name: temp increase /tmp size
      tags: always
      shell: mount -o remount,size=5G,noatime /tmp

    - name: install reflector package
      pacman:
        name: reflector
        state: present

    - name: Create the aur_builder user
      ansible.builtin.user:
        name: aur_builder
        group: wheel
        create_home: yes

    - name: Configure sudoers for aur_builder
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: yes
        mode: 0644
        validate: 'visudo -cf %s'

    - name: Install paru using makepkg
      kewlfft.aur:
        name: paru
        use: makepkg
        state: present
      become: yes
      become_user: aur_builder

  roles:
    - { role: configure, tags: configure }
    - { role: pacman, tags: pacman }
    - { role: rustup, tags: rustup }
    - { role: cronie, tags: cronie }
    - { role: ansible_user, tags: ansible_user }
    - { role: base, tags: base }
    - { role: bash, tag: bash }
    - { role: desktop, tags: desktop }
    - { role: mpv, tag: mpv }
