---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:

    # Fix full /tmp when installing lots of AUR
    - name: temp increase /tmp size
      tags: always
      shell: mount -o remount,size=5G,noatime /tmp

    - name: install reflector package
      pacman:
        name: reflector
        state: present

  roles:
    - { role: pacman, tags: pacman }
    - { role: ansible_user, tags: ansible_user }
    - { role: base, tags: base }
    - { role: bash, tag: bash }
    - { role: cronie, tags: cronie }
    - { role: desktop, tags: desktop }
    - { role: mpv, tag: mpv }
