---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:

    # Fix full /tmp when installing lots of AUR
    - name: temp increase /tmp size
      tags: always
      shell: mount -o remount,size=5G,noatime /tmp

  roles:
    - { role: ansible_user, tags: asnible_user }
    - { role: base, tags: base }
    - { role: bash, tag: bash }
    - { role: cronie, tags: cronie }
    - { role: desktop, tags: desktop }
    - { role: mpv, tag: mpv }
