---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:

    # Fix full /tmp when installing lots of AUR
    - name: temp increase /tmp size
      tags: always
      shell: mount -o remount,size=5G,noatime /tmp

    - name: install reflector package
      pacman:
        name: reflector
        state: present

  roles:
    - { role: pacman, tags: pacman }
    - { role: rustup, tags: rustup }
    - { role: cronie, tags: cronie }
    - { role: ansible_user, tags: ansible_user }
    - { role: aur, tags: aur }
    - { role: aur_helper, tags: aur_helper }
    - { role: base, tags: base }
    - { role: bash, tag: bash }
    - { role: desktop, tags: desktop }
    - { role: mpv, tag: mpv }
