- name: install audio packages
  pacman:
    name:
      - pipewire
      - pipewire-pulse
      - pipewire-alsa
      - wireplumber
      - pavucontrol
      - pamixer
      - alsa-utils
    state: present

- name: install applications packages
  pacman:
    name:
      - mpv
      - 7zip
    state: present

-  name: Install niri
   pacman:
     name:
       - niri
       - fuzzel
       - mako
       - waybar
       - xdg-desktop-portal-gtk
       - xdg-desktop-portal-gnome
       - alacritty
       - swaybg
       - swayidle
       - swaylock
       - xwayland-satelite
       - udiskie
       - ironbar
