- name: install audio packages
  community.general.pacman:
    name:
      - pipewire
      - pipewire-pulse
      - pipewire-alsa
      - wireplumber
      - pavucontrol
      - pamixer
      - alsa-utils
    state: present

- name: install applications packages
  community.general.pacman:
    name:
      - mpv
      - 7zip
    state: present

-  name: Install niri
   community.general.pacman:
     name:
       - niri
       - fuzzel
       - mako
       - waybar
       - xdg-desktop-portal-gtk
       - xdg-desktop-portal-gnome
       - alacritty
       - swaybg
       - swayidle
       - swaylock
       - xwayland-satellite
       - udiskie
       - ironbar

- name: install handlr for default applications
  community.general.pacman:
    name:
      - handlr-regex
    state: present


