- name: Install packages with Shell-CLI
  ansible.builtin.command: shelly install htop --no-confirm
  tty: true
  become: true
  become_method: su
  become_user: root
  become_flags: '-s /bin/sh'
#- name: Install AUR package
#  become: yes
#  become_user: chaos
#  community.general.pacman:
#    name: tt-ms-fonts
#    state: present
#    executable: yay
#    extra_args: --builddir /var/cache/yay
#- name: Uprgrade the whole system
#  community.general.pacman:
#    upgrade: true
#    executable: yay
#    update_cache: true
#    extra_args: --removemake --cleanafter --noconfirm
#

