- name: Install packages with Shell-CLI
  become: true
  become_user: chaos
  ansible.builtin.command: |
    shelly install "{{ item }}" --no-confirm
  loop:
    - htop

#- name: Install AUR package
#  become: yes
#  become_user: chaos
#  community.general.pacman:
#    name: tt-ms-fonts
#    state: present
#    executable: yay
#    extra_args: --builddir /var/cache/yay
#- name: Uprgrade the whole system
#  community.general.pacman:
#    upgrade: true
#    executable: yay
#    update_cache: true
#    extra_args: --removemake --cleanafter --noconfirm
#

