- name: Install AUR package
  community.general.pacman:
    name: downgrade
    state: present
    executable: yay
    extra_args: --builddir /var/cache/yay
#- name: Uprgrade the whole system
#  community.general.pacman:
#    upgrade: true
#    executable: yay
#    update_cache: true
#    extra_args: --removemake --cleanafter --noconfirm
#
#- name: Install AUR packages
#  ansible.builtin.command: |
#    yay --noconfirm --noprogressbar --cleanafter --removemake --needed --sync "{{ item }}"
#  loop:
#    - downgrade
