- name: Install walker
  ansible.builtin.unarchive:
    src: https://github.com/abenz1267/walker/releases/download/v2.16.0/walker-v2.16.0-x86_64-unknown-linux-gnu.tar.gz
    dest: /usr/local/bin
    remote_src: true
    mode: "0755"
  become: true
