- user: name=aur_builder

- lineinfile:
    path: /etc/sudoers.d/aur_builder-allow-to-sudo-pacman
    state: present
    line: "aurbuilder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    validate: /usr/sbin/visudo -cf %s
    create: yes

#- aur: name=yay
#  become: yes
#  become_user: aurbuilder
#
- aur: name=ttf-ms-fonts
  become: yes
  become_user: aur_builder
