- name: Install paru AUR helper
  shell: | 
    git clone https://aur.archlinux.org/paru.git
    cd pau
    makepkg -si
  args:
    chdir: "/home/chaos/paru/"
  become: yes
  become_user: "chaos"
  register: paru_install
  changed_when: paru_install.r == 0
