- name: install base packages
  community.general.pacman:
    name:
      - dotnet-sdk
      - fzf
      - less
      - man-pages
      - man-db
      - python-passlib
      - udisks2
      - wl-clipboard
    state: present

- name: install base packages (Rust CLI)
  community.general.pacman:
    name:
      - bat
      - bat-extras
      - eza
      - fd
      - ripgrep
      - ripgrep-all
      - repgrep
      - vivid
      - yazi
      - zoxide
    state: present

- name: install base packages (apparmor)
  community.general.pacman:
    name:
      - apparmor
      - audit
      - python-notify2
      - python-psutil
      - tk
    state: present
