#- mame: create alacritty config dir
#  file:
#    path: "{{ ansible_env.HOME }}/.config/alacritty"
#    state: directory
#    owner: chaos
#    group: chaos
#
#- name: copy alacritty config file
#  copy:
#    src: alacritty.toml
#    dest: "{{ ansible_env.HOME }}/.config/alacritty"
#    owner: chaos
#    group: chaos
