- name: create alacritty config dir
  file:
    path: /home/chaos/.config/alacritty
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: copy alacritty config file
  copy:
    src: alacritty.toml
    dest: /home/chaos/.config/alacritty
    owner: chaos
    group: chaos
