- name: create alacritty config dir
  file:
    path: "/home/{{ user }}/.config/alacritty"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: copy alacritty config file
  copy:
    src: alacritty.toml
    dest: "/home/{{ user }}/.config/alacritty"
    owner: "{{ user }}"
    group: "{{ user }}"
